### ISSUE TITLE
Saving app secret to localStorage probably a bad idea

### ISSUE THREAD

**Issue by davidmurdoch** [mach-kernel/dwolla-token-generator#8]
Love this app! I've got an app that has no UI (and no need for one), and this has saved me tons of time generating the initial access tokens. However, for security reasons I don't think the app secret should be saved to localStorage, at least not without opting in. I use 2FA and strong passwords for everything under the sun, but now my browser has everything an attacker needs to completely drain my Dwolla funds!

What do you think about adding a check box like "Remember Application Key and Secret"?

**Comment by mach-kernel** [comment]
Hi there @davidmurdoch,

I don't think that there is any significant risk here. An attacker would have to reverse HSTS to gain access to your session storage. You could easily argue that the token being a part of your DOM could also be a risk because of some sort of rogue browser extension that just awaits the generation of your token.

**Comment by davidmurdoch** [comment]
I'm escalating this to security@dwolla.com.

I'm more concerned about spyware that silently transmits browser data or backups in the background.

The fact remains, you are essentially storing a password in plaintext and not telling the user you are doing it. And it's a password that bypasses 2FA!

It also isn't crazy to think someone could use this tool on a public computer (University library or lab, maybe), causing what is essentially his username and password for Dwolla to be stored in plaintext in the browser.
